name: deploy

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["build"]
    types: [completed]

jobs:
  publish:
    if: >
      github.event.workflow_run.conclusion == 'success' &&
      github.event.workflow_run.event == 'push' &&
      github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
          cache: true
          cache-dependency-path: |
            src/Planara.Kafka/packages.lock.json

      - name: Restore
        run: dotnet restore Planara.Kafka.sln

      - name: Build
        run: dotnet build Planara.Kafka.sln -c Release --no-restore

      - name: Pack
        run: dotnet pack src/Planara.Kafka/Planara.Kafka.csproj -c Release --no-build -o ./nupkg

      - name: Push to NuGet.org
        env:
          NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        run: |
          dotnet nuget push "./nupkg/*.nupkg" \
            --api-key "$NUGET_TOKEN" \
            --source "https://api.nuget.org/v3/index.json" \
            --skip-duplicate

      - name: Push to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          dotnet nuget push "./nupkg/*.nupkg" \
            --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
            --api-key "$GITHUB_TOKEN" \
            --skip-duplicate